#276 Fix memory access violation when parsing datetime types
nanodbc/nanodbc pull request #360
Opened 2022-11-14 16:32 UTC by matejbrumen

## What does this PR do?

This PR fixes memory access violation when changing locale state inside `SQL_C_DATE`, `SQL_C_TIME` and `SQL_C_TIMESTAMP` cases in function `result::result_impl::get_ref_impl` by storing copy of the old locale.

## What are related issues/pull requests?

Related issue is #276 where problem is also explained in details.

## Other

I ran only `mssql_tests.exe` where existing tests passed with the following output:

```
All tests passed (28297 assertions in 74 test cases)                           
```

## Environment

* DBMS name/version: SQLExpress
* ODBC connection string: Driver={ODBC Driver 17 for SQL Server};Server=localhost\SQLEXPRESS;Database=nanodbc;Trusted_Connection=Yes;Encrypt=No;TrustServerCertificate=Yes;
* OS and Compiler: Windows10, MSVC (v143)

2022-11-14 16:50 UTC, mloskot requested changes
Thank you for your contribution, but this does not look good to me, I'm afraid.

2022-11-14 17:57 UTC, matejbrumen commented on nanodbc/nanodbc.cpp
> +        std::setlocale(LC_TIME, old_lc_time.c_str());
Ok, I changed the code even though it states that "If locale is a null pointer, setlocale queries the current C locale without modifying it.". I'd assume that in this case it always returns the valid locale. 

Thanks for suggestion.

2022-11-14 19:07 UTC, matejbrumen commented on nanodbc/nanodbc.cpp
> +        std::setlocale(LC_TIME, old_lc_time.c_str());
No, the original problem occurred on the line below at ```std::setlocale(LC_TIME, "");``` which frees the old_lc_time memory which is then used at the last `std::setlocale` (use after free).

Please correct me if I'm wrong but `std::string old_lc_time = std::setlocale(LC_TIME, nullptr);` should always return valid address and never null. I'm not aware of any implementation that returns nullptr in such case. But in the end it doesn't hurt to check for null.

2022-11-15 16:42 UTC, mloskot approved these changes
Thank you

2022-11-15 16:50 UTC, merged